---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 471112520049.dkr.ecr.us-east-1.amazonaws.com/nginx:3
        ports:
        - containerPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service
#spec:
#  type: NodePort 
#  selector:
#    app: nginx 
#  ports:
#   - protocol: TCP
#      port: 80           
#      targetPort: 80     
#      nodePort: 32007  

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing  # Balanceador accesible desde Internet
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer