name: ECR Test CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'service/app/**' 

env:
  AWS_REGION: us-east-1
  REPOSITORY_URI: 471112520049.dkr.ecr.us-east-1.amazonaws.com/nginx
  IMAGE_TAG: ${{ github.run_number }} # GitHub run number as a unique image tag

permissions:
  id-token: write 
  contents: read  

jobs:
  eks-ecr-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::471112520049:role/github-actions-role
          role-session-name: ecrrolesessiontemp
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.REPOSITORY_URI }}

      - name: Build and Push Docker Image
        working-directory: ./service 
        run: |
          docker build -t ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }}

      - name: Checking AWS CLI config
        run: |
          aws configure list

      - name: Success Message
        run: echo "La imagen se pusheó con éxito al repositorio ECR"
