name: ECR Test CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'eks/**'  

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write 
  contents: read  

jobs:
  eks-ecr-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::471112520049:role/github-actions-role
          role-session-name: ecrrolesessiontemp
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Success Message
        run: echo "Success!"