name: ECR Test CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'eks/**'  

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write 
  contents: read  

jobs:
  eks-ecr-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423456632:role/github-actions-role
          role-session-name: ecrrolesessiontemp
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.0"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./eks
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
        working-directory: ./eks

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./eks

      - name: Success Message
        run: echo "Success!"